<script setup lang="js">
import { ref, watch, onMounted, onUnmounted, computed } from 'vue'
import Papa from 'papaparse'

const count = ref(0)
const link = ref('https://github.com/guocaoyi/create-chrome-ext')
let storeData = ref([])
const filterDate = ref(new Date())
const minus = () => {
  if (count.value > 0) count.value--
}
const add = () => count.value++

onMounted(() => {
  chrome.storage.sync.get(['count'], (result) => {
    count.value = result.count || 0
  })
})

watch(count, (newCount) => {
  chrome.storage.sync.set({ count: newCount })

  chrome.runtime.sendMessage({ type: 'COUNT', count: count.value })
})

const readstorage = () => {
  chrome.storage.local.get(["key"]).then((result) => {
    console.log(JSON.parse(result.key));
  });
}

const readCsv = () => {
  const fileInput = document.getElementById('fileInput')
  const file = fileInput.files[0]

  if (file) {
    const reader = new FileReader()

    reader.onload = (e) => {
      const content = e.target.result

      // 使用 Papa.parse 將 CSV 轉換為 JSON
      Papa.parse(content, {
        complete: (result) => {
          storeData = result.data
          console.log(storeData)
          console.log(todayStore.value)  
          chrome.storage.local.set({ "key": JSON.stringify(todayStore.value) }).then(() => {
            console.log("Value is set");
          });
        },
        header: true
      })
    }

    reader.readAsText(file)
  }
}

const todayStore = computed(() => {
  // 使用过滤函数筛选 JSON 数组
  const result = storeData.filter(item => {
    // 将日期字符串转换为 Date 对象
    const itemDate = new Date(item.數網施工日期)
    
    // 比较年、月、日是否相同
    return (
      itemDate.getFullYear() === filterDate.value.getFullYear() &&
      itemDate.getMonth() === filterDate.value.getMonth() &&
      itemDate.getDate() === filterDate.value.getDate()
    )
  })

  const groupedData = result.reduce((acc, item) => {
    if (!acc[item.門市名稱]) {
      acc[item.門市名稱] = item;
      acc[item.門市名稱]["螢幕"] = [];
    }

    if (item.裝置名稱1!=="") {
      acc[item.門市名稱]["螢幕"].push({"name" : item.裝置名稱1, "位置": item.位置1});
    }
    if (item.裝置名稱2!=="") {
      acc[item.門市名稱]["螢幕"].push({"name" : item.裝置名稱2, "位置": item.位置2});
    }
    return acc;
  }, {});
  

  const storeByCrew = Object.values(groupedData).reduce((acc, item) => {
    if (!acc[item.施作廠商]) {
      acc[item.施作廠商] = [];
    }
    acc[item.施作廠商].push(item)
    return acc;
  }, {});


  return storeByCrew
})
</script>

<template>
  <main>
    <h3>Popup Page</h3>

    <div class="calc">
      <button @click="minus" :disabled="count <= 0">-</button>
      <label>{{ count }}</label>
      <button @click="add">+</button>
    </div>

    <body>
      <input type="file" id="fileInput" />
      <button @click="readCsv" >Read csv</button>
      <button @click="readstorage" >Readstorage</button>
    </body>

    <a :href="link" target="_blank"> generated by create-chrome-ext </a>
  </main>
</template>

<style>
:root {
  font-family:
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    'Segoe UI',
    Roboto,
    Oxygen,
    Ubuntu,
    Cantarell,
    'Open Sans',
    'Helvetica Neue',
    sans-serif;

  color-scheme: light dark;
  background-color: #242424;
}

@media (prefers-color-scheme: light) {
  :root {
    background-color: #fafafa;
  }

  a:hover {
    color: #42b983;
  }
}

body {
  min-width: 20rem;
  color-scheme: light dark;
}

main {
  text-align: center;
  padding: 1em;
  margin: 0 auto;
}

h3 {
  color: #42b983;
  text-transform: uppercase;
  font-size: 1.5rem;
  font-weight: 200;
  line-height: 1.2rem;
  margin: 2rem auto;
}

.calc {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 2rem;

  > button {
    font-size: 1rem;
    padding: 0.5rem 1rem;
    border: 1px solid #42b983;
    border-radius: 0.25rem;
    background-color: transparent;
    color: #42b983;
    cursor: pointer;
    outline: none;

    width: 3rem;
    margin: 0 a;
  }

  > label {
    font-size: 1.5rem;
    margin: 0 1rem;
  }
}

a {
  font-size: 0.5rem;
  margin: 0.5rem;
  color: #cccccc;
  text-decoration: none;
}
</style>
